# Generated by Django 3.2.9 on 2021-11-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historia_clinica", "0002_patologia"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="apellido_1",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name="paciente",
            name="apellido_2",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="direccion",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="documento",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="paciente",
            name="estartura",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
        migrations.AddField(
            model_name="paciente",
            name="peso",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
        migrations.AddField(
            model_name="paciente",
            name="telefono",
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nombre",
            field=models.CharField(max_length=30),
        ),
    ]
