# Generated by Django 3.2.9 on 2021-11-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("historia_clinica", "0002_evoluciones_procedimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="evoluciones",
            name="paciente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="historia_clinica.paciente",
            ),
        ),
        migrations.AddField(
            model_name="evoluciones",
            name="procedimiento",
            field=models.ManyToManyField(to="historia_clinica.Procedimiento"),
        ),
    ]
