# Generated by Django 3.2.9 on 2021-11-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historia_clinica", "0003_auto_20211122_1818"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="patologia",
            field=models.ManyToManyField(to="historia_clinica.Patologia"),
        ),
    ]
