# Generated by Django 3.2.9 on 2021-11-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historia_clinica", "0005_alter_patologia_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="grupo_sanguineo",
            field=models.IntegerField(
                choices=[
                    (1, "O-"),
                    (2, "O+"),
                    (3, "A-"),
                    (4, "A+"),
                    (5, "B-"),
                    (6, "B+"),
                    (7, "AB-"),
                    (8, "AB+"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paciente",
            name="apellido_1",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefono",
            field=models.CharField(max_length=15),
        ),
    ]
