# Generated by Django 3.2.9 on 2021-11-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("historia_clinica", "0007_alter_procedimiento_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evoluciones",
            name="paciente",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="historia_clinica.paciente",
            ),
            preserve_default=False,
        ),
    ]
