# Generated by Django 3.2.9 on 2021-11-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0006_auto_20211122_1928'),
        ('historia_clinica', '0008_alter_evoluciones_paciente'),
    ]

    operations = [
    ]
