# Generated by Django 3.2.9 on 2021-11-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historia_clinica", "0009_merge_20211122_2049"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDocIdentificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=25, unique=True)),
                ("nombreCorto", models.CharField(max_length=4, unique=True)),
            ],
        ),
    ]
