# Generated by Django 3.2.9 on 2021-11-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("historia_clinica", "0010_tipodocidentificacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=30)),
                ("correo", models.EmailField(max_length=30)),
                ("nombre", models.CharField(max_length=20)),
                ("apellido_1", models.CharField(max_length=30)),
                ("apellido_2", models.CharField(blank=True, max_length=30, null=True)),
                ("doc_identificacion", models.CharField(max_length=20, unique=True)),
                (
                    "tipo_doc_identificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="historia_clinica.tipodocidentificacion",
                    ),
                ),
            ],
        ),
    ]
