# Generated by Django 3.2.9 on 2021-12-11 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("historia_clinica", "0011_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="evoluciones",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="historia_clinica.usuario",
            ),
            preserve_default=False,
        ),
    ]
