# Generated by Django 3.2.9 on 2021-12-12 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historia_clinica", "0013_auto_20211212_0140"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnostico",
            name="fecha",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="diagnostico",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
    ]
