# Generated by Django 3.2.9 on 2021-12-12 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("historia_clinica", "0014_auto_20211212_0147"),
    ]

    operations = [
        migrations.AddField(
            model_name="evoluciones",
            name="diagnostico",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="historia_clinica.diagnostico",
            ),
            preserve_default=False,
        ),
    ]
