# Generated by Django 3.2.9 on 2021-12-12 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("historia_clinica", "0015_evoluciones_diagnostico"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evoluciones",
            name="paciente",
        ),
    ]
