# Generated by Django 3.2.9 on 2021-12-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historia_clinica", "0017_auto_20211212_0324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="patologia",
            field=models.ManyToManyField(blank=True, to="historia_clinica.Patologia"),
        ),
    ]
