import local_apps.historia_clinica.models.evoluciones
import local_apps.historia_clinica.models.paciente
import local_apps.historia_clinica.models.patologia
import local_apps.historia_clinica.models.procedimiento
